/* Page rendering. Everything numeric comes from DATA, which is generated by
   analysis/export_web_data.py from stored run directories — so no figure here
   can disagree with the runs it claims to describe. */

const $ = sel => document.querySelector(sel);
let state = { metric: "resident_trait_retention", rules: ["null", "axelrod_homophily", "conformist"] };

function cell(rule, k) { return DATA.cells[rule + "|" + k]; }
function metricMeta(key) { return DATA.metrics.find(m => m.key === key) || { label: key, units: "" }; }
function isRetention(key) { return key === "resident_trait_retention"; }

/* ---------------------------------------------------------------- results */
function renderResults() {
  const d = DATA.design;
  $("#result-toolbar").innerHTML =
    `<div class="field"><span>Measurement</span><div class="seg" id="metric-seg">` +
    DATA.metrics.map(m =>
      `<button type="button" data-metric="${m.key}" aria-pressed="${m.key === state.metric}">${m.label}</button>`
    ).join("") + `</div></div>`;

  $("#metric-seg").addEventListener("click", e => {
    const b = e.target.closest("button[data-metric]");
    if (!b) return;
    state.metric = b.dataset.metric;
    renderResults();
  });

  const meta = metricMeta(state.metric);
  const ref = isRetention(state.metric) ? DATA.compositional_baseline : null;

  /* strip plot: every run, grouped by rule then source count */
  const groups = [];
  state.rules.forEach(rule => {
    d.source_counts.forEach(k => {
      const c = cell(rule, k);
      if (!c) return;
      groups.push({
        label: `${DATA.design.rule_labels[rule].replace(" (control)", "")} · K=${k}`,
        values: c[state.metric].values,
        colour: RULE_COLOUR[rule]
      });
    });
  });

  $("#strip").innerHTML =
    stripPlot(groups, {
      reference: ref,
      referenceLabel: "composition only",
      dp: state.metric === "cultural_richness" || state.metric === "cultural_effective_number" ? 0 : 2,
      aria: meta.label + " for every run, grouped by mechanism and source count"
    }) +
    `<figcaption>${meta.label} — one mark per run (${d.replicates} seeds per cell), heavy rule at the group mean. ` +
    (ref !== null
      ? `The dashed line is what composition alone predicts: <code>1 − M·D = ${DATA.compositional_baseline}</code>. An arm sitting on it is doing arithmetic, not culture.`
      : `Units: ${meta.units}.`) +
    `</figcaption>`;

  /* lines: the same metric against K */
  const series = state.rules.map(rule => ({
    label: d.rule_labels[rule],
    short: RULE_SHORT[rule],
    colour: RULE_COLOUR[rule],
    points: d.source_counts.map(k => {
      const c = cell(rule, k);
      return { mean: c ? c[state.metric].mean : 0, se: c ? c[state.metric].se : 0 };
    })
  }));
  $("#lines").innerHTML =
    contrastLines(series, {
      x: d.source_counts,
      xlabel: "K — number of distinct incoming cultures (total migration held at " + d.migration_share + ")",
      reference: ref,
      referenceLabel: "composition",
      dp: state.metric === "cultural_richness" || state.metric === "cultural_effective_number" ? 0 : 2,
      aria: meta.label + " against source count, one line per mechanism"
    }) +
    `<figcaption>Bars are one standard error. The x-axis is the project's central manipulation: the ` +
    `same number of arrivals, split into more or fewer cultures.</figcaption>`;

  /* the contrast table */
  $("#contrast-table").innerHTML =
    `<table><thead><tr><th>Mechanism</th><th class="num">K=${d.source_counts[0]}</th>` +
    `<th class="num">K=${d.source_counts[d.source_counts.length - 1]}</th>` +
    `<th class="num">Difference</th><th class="num">Std. error</th><th class="num">z</th></tr></thead><tbody>` +
    state.rules.map(rule => {
      const c = DATA.contrasts[rule];
      const lo = cell(rule, d.source_counts[0]);
      const hi = cell(rule, d.source_counts[d.source_counts.length - 1]);
      if (!c || !lo || !hi) return "";
      return `<tr><td>${d.rule_labels[rule]}</td>` +
        `<td class="num">${FMT(lo[state.metric].mean, 4)}</td>` +
        `<td class="num">${FMT(hi[state.metric].mean, 4)}</td>` +
        (isRetention(state.metric)
          ? `<td class="num">${c.diff > 0 ? "+" : ""}${FMT(c.diff, 4)}</td><td class="num">${FMT(c.se, 4)}</td><td class="num">${c.z === null ? "—" : FMT(c.z, 2)}</td>`
          : `<td class="num dim">—</td><td class="num dim">—</td><td class="num dim">—</td>`) +
        `</tr>`;
    }).join("") + `</tbody></table>`;
}

/* ------------------------------------------------------------ mechanisms */
function renderMechanisms() {
  $("#mechanisms-cards").innerHTML = DATA.design.rules.map(rule => {
    const t = RULE_TEXT[rule];
    const c = cell(rule, DATA.design.source_counts[0]);
    const ret = c ? c.resident_trait_retention.mean : null;
    return `<div class="card">
      <p class="ptitle" style="color:${RULE_COLOUR[rule]}">${DATA.design.rule_labels[rule]}</p>
      <p style="margin:0 0 8px;font-weight:600">${t.rule}</p>
      <p style="margin:0 0 12px;color:var(--rf-ink-dim)">${t.body}</p>
      <div class="tablewrap"><table><tbody>
        <tr><td>Resident cultural retention at K=1</td><td class="num">${FMT(ret, 4)}</td></tr>
        <tr><td>Composition alone predicts</td><td class="num">${DATA.compositional_baseline}</td></tr>
      </tbody></table></div>
    </div>`;
  }).join("");
}

/* ------------------------------------------------------------ provenance */
function renderProvenance() {
  const b = DATA.batch, d = DATA.design;
  $("#prov-spec").innerHTML = [
    ["Model version", DATA.model_version],
    ["Runs", b.n_runs + " (" + (b.failures || "no") + " failures)"],
    ["Replicates per cell", d.replicates + " seeds"],
    ["Population", d.population + " agents"],
    ["Culture", d.features + " features × " + d.traits + " traits"],
    ["Migration", "share " + d.migration_share + ", distance " + d.cultural_distance],
    ["Drift rate", d.drift],
    ["Conformity exponent", d.conformity],
    ["Simulated span", d.years + " years"],
    ["Compute", Math.round(b.compute_seconds) + " s"],
    ["Batch finished", b.finished_utc.slice(0, 16).replace("T", " ") + " UTC"],
    ["Source", DATA.generated_from]
  ].map(r => `<tr><td>${r[0]}</td><td class="num">${r[1]}</td></tr>`).join("");

  $("#prov-runs").innerHTML =
    `<table><thead><tr><th>Mechanism</th><th class="num">K</th><th class="num">Seed</th>` +
    `<th>Config hash</th><th>Run hash</th></tr></thead><tbody>` +
    DATA.provenance.map(p =>
      `<tr><td>${RULE_SHORT[p.rule] || p.rule}</td><td class="num">${p.k}</td><td class="num">${p.seed}</td>` +
      `<td class="mono dim">${p.config_hash.slice(0, 12)}</td><td class="mono dim">${p.run_hash.slice(0, 12)}</td></tr>`
    ).join("") + `</tbody></table>`;

  $("#prov-assumptions").innerHTML = KEY_ASSUMPTIONS.map(a =>
    `<tr><td class="mono">${a[0]}</td><td>${a[1]}</td></tr>`
  ).join("");
}
